version: "3.1"

services:
  www:
    container_name: projects-monitor
    build: .
    ports:
      - "8009:80"
    volumes:
      - ./Src:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - default

volumes:
  my-db:
