version: "3.1"

services:
  www:
    build: .
    ports:
      - "8005:80"
    volumes:
      - ./Src:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - default