services:
  web:
    container_name: projects-monitor-web
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./Src:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - default

  database:
    container_name: projects-monitor-database
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test
      MARIADB_USER: test
      MARIADB_PASSWORD: test
    volumes:
      - projects-monitor-db:/var/lib/mysql
    networks:
      - default

volumes:
  projects-monitor-db:
