sonar.organization=guibranco
sonar.projectKey=guibranco_projects-monitor

sonar.sources=Src
sonar.tests=Tests/UnitTests
sonar.exclusions=Src/vendor/**,Src/cache/**,Src/secrets/**
sonar.php.coverage.reportPaths=coverage.xml
