name: JSON/YAML validation

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  json-yaml-validate:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v5

      - name: json-yaml-validate
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v4.0.0
        with:
          comment: "true"
