name: PHP Linting

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  php-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Check PHP Lint
        uses: fxpw/PHP-Lint-php8.3@8271244b22510b60b5ccb1f780a9c729d332a504 # master
