name: Shell checker

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  shell-checker:
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Shellcheck
        run: shellcheck **/*.sh
