name: Label based on PR size

on:
  pull_request:
  workflow_dispatch:
  
jobs:
  size-label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    steps:

      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
